import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <div className="ml-[10vw] mr-[10vw]  w-[80vw] h-max border border-blue-500 flex items-start flex-wrap gap-x-3 gap-y-20 ">
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
        </div> */}
        <div className="ml-[5vw] mr-[5vw] mt-[10vw] w-[90vw] h-max  flex justify-center   ">
          <div className="w-[80vw] h-max grid grid-cols-1 md:grid-cols-3 gap-20 ">
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
